name: Publish Docker Images

on:
  push:
    tags:
      - v1.[0-9]+.[0-9]+

jobs:
  publish:
    strategy:
      matrix:
        distro: [buster]
        flavor: [fs]
      max-parallel: 2
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@master
    - name: Get version from tag
      id: get_version
      run: echo ::set-env name=VERSION::$(echo ${GITHUB_REF#*/v})
    - name: Get major version
      id: get_major_version
      run: echo ::set-env name=MAJOR_VERSION::$(echo ${{ env.VERSION }} | grep -o '[^-]*$' | cut -d. -f1)
    - name: Get minor version
      id: get_minor_version
      run: echo ::set-env name=MINOR_VERSION::$(echo ${{ env.VERSION }} | grep -o '[^-]*$' | cut -d. -f2)
    - name: Get major_minor version
      id: get_major_minor_version
      run: echo ::set-env name=MAJOR_MINOR_VERSION::$(echo ${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }})
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: cmontemuino/mlflow
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ${{ env.MAJOR_MINOR_VERSION }}/${{ matrix.distro }}/${{ matrix.flavor }}
        buildargs: MLFLOW_VERSION=${{ env.VERSION }}
        buildoptions: "--label GITHUB_SHA=${GITHUB_SHA} --label MLFLOW_RELEASE=https://github.com/mlflow/mlflow/releases/tag/${{ env.VERSION }}"
        tags: "${{ env.VERSION }}-${{ matrix.distro }}-${{ matrix.flavor }},${{ env.MAJOR_MINOR_VERSION }}-${{ matrix.distro }}-${{ matrix.flavor }}"
